# basic options
title: Nirosha Rathnayake
author: niroshar
email: niro.uno@gmail.com
description: Welcome !
twitter_username: NiroshaRathnay2
github_username: niroshar

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
